name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build
        run: dub build --build=release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fzf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
